# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.12.0
_src_path: https://github.com/Escodoo/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
github_check_license: true
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_version: 14.0
org_name: Escodoo
org_slug: Escodoo
rebel_module_groups: []
repo_description: 'Escodoo add-ons used to extend or customize Odoo Base app functions.'
repo_name: Base Addons
repo_slug: base-addons
repo_website: https://github.com/Escodoo/base-addons
travis_apt_packages: []
travis_apt_sources: []
