# Copyright 2024 - TODAY, Escodoo
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

{
    "name": "Escodoo Setup Base BR",
    "summary": """
        Escodoo Setup Base BR""",
    "version": "14.0.1.0.0",
    "license": "AGPL-3",
    "author": "Escodoo",
    "website": "https://github.com/Escodoo/base-addons",
    "depends": [
        "escodoo_setup_base",
        "l10n_br_account_due_list",
        "l10n_br_account_fleet",
        "l10n_br_account_nfe",
        "l10n_br_account_payment_brcobranca",
        "l10n_br_account_payment_order",
        "l10n_br_base",
        "l10n_br_cnpj_search",
        "l10n_br_cnab_structure",
        "l10n_br_coa",
        "l10n_br_coa_generic",
        "l10n_br_coa_simple",
        "l10n_br_contract",
        "l10n_br_crm",
        "l10n_br_cte_spec",
        "l10n_br_currency_rate_update",
        "l10n_br_delivery",
        "l10n_br_delivery_nfe",
        "l10n_br_fiscal",
        "l10n_br_fiscal_certificate",
        "l10n_br_fiscal_closing",
        "l10n_br_fiscal_dfe",
        "l10n_br_hr",
        "l10n_br_ie_search",
        "l10n_br_mdfe_spec",
        "l10n_br_mis_report",
        "l10n_br_nfe",
        "l10n_br_nfe_spec",
        "l10n_br_nfse",
        "l10n_br_portal",
        "l10n_br_product_contract",
        "l10n_br_purchase",
        "l10n_br_purchase_request",
        "l10n_br_purchase_stock",
        "l10n_br_resource",
        "l10n_br_sale",
        "l10n_br_sale_blanket_order",
        "l10n_br_sale_invoice_plan",
        "l10n_br_sale_stock",
        "l10n_br_stock",
        "l10n_br_stock_account",
        "l10n_br_stock_account_report",
        "l10n_br_zip",
        "spec_driven_model",
    ],
    "data": [],
    "demo": [],
}
