# Copyright 2024 - TODAY, Escodoo
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

{
    "name": "Escodoo Setup Base",
    "summary": """
        Escodoo Odoo Setup Base""",
    "version": "14.0.1.0.0",
    "license": "AGPL-3",
    "author": "Escodoo",
    "website": "https://github.com/Escodoo/base-addons",
    "depends": [
        "account_analytic_required",
        "account_asset_management",
        "account_asset_management_fleet",
        "account_due_list",
        "account_due_list_payment_mode",
        "account_financial_report",
        "account_lock_date_update",
        "account_lock_to_date",
        "account_menu",
        "account_move_base_import",
        "account_move_csv_import",
        "account_move_line_cash_basis_report",
        "account_move_line_menu",
        "account_move_template",
        "account_move_visible_date_maturity",
        "account_payment",
        "account_payment_order",
        "account_payment_partner",
        "account_payment_paired_internal_transfer",
        "account_reconciliation_widget",
        "account_statement_import_ofx_by_acctid",
        "auth_admin_passkey",
        "base",
        "base_address_city",
        "base_address_extended",
        "base_automation",
        "base_setup",
        "base_technical_features",
        "bi_sql_editor",
        "contacts",
        "contract",
        "crm",
        "currency_rate_update",
        "date_range",
        "date_range_account",
        "delivery",
        "delivery_carrier_partner",
        "fleet_vehicle_calendar_year",
        "fleet_vehicle_category",
        "fleet_vehicle_fuel_capacity",
        "fleet_vehicle_log_fuel",
        "fleet_vehicle_fuel_type_ethanol",
        "fleet_vehicle_history_date_end",
        "fleet_vehicle_inspection_template",
        "fleet_vehicle_notebook",
        "fleet_vehicle_pivot_graph",
        "fleet_vehicle_service_calendar",
        "fleet_vehicle_service_kanban",
        "fleet_vehicle_stock",
        "gamification_badge_report",
        "hr",
        "hr_contract",
        "hr_contract_document",
        "hr_contract_type",
        "hr_course",
        "hr_course_survey",
        "hr_employee_age",
        "hr_employee_document",
        "hr_employee_medical_examination",
        "hr_employee_ppe",
        "hr_expense_advance_clearing",
        "hr_expense_invoice",
        "hr_expense_journal",
        "hr_expense_remove_mobile_link",
        "hr_personal_equipment_request",
        "hr_skills",
        "hr_timesheet_sheet",
        "mail_tracking",
        "mail_tracking_mass_mailing",
        "mass_mailing",
        "mass_mailing_resend",
        "marketing_crm_partner",
        "mis_builder",
        "mis_builder_analytic",
        "mis_builder_budget",
        "mis_builder_cash_flow_by_month",
        "mis_builder_cash_flow_forecast_contract",
        "mis_builder_cash_flow_forecast_integration",
        "mis_builder_cash_flow_forecast_purchase",
        "mis_builder_cash_flow_forecast_sale",
        "mis_builder_cash_flow_forecast_sale_invoice_plan",
        "mis_template_financial_report",
        "portal",
        "product",
        "product_contract",
        "product_expiry",
        "purchase",
        "purchase_default_terms_conditions",
        "purchase_order_line_menu",
        "purchase_order_line_stock_available",
        "purchase_report_menu_move",
        "purchase_request",
        "purchase_work_acceptance_evaluation",
        "quality_control_stock_oca",
        "remove_odoo_enterprise",
        "resource",
        "sale",
        "sale_blanket_order",
        "sale_invoice_plan",
        "sale_management",
        "sale_stock",
        "sale_transaction_form_link",
        "scrap_reason_code",
        "session_db",
        "sign_oca",
        "survey",
        "stock",
        "stock_account",
        "stock_landed_costs",
        "stock_picking_analytic",
        "stock_picking_invoicing",
        "stock_request",
        "stock_request_purchase_request",
        "supplier_quality_index",
        "web_advanced_search",
        "web_escodoo_brand",
        "web_pwa_oca",
        "web_responsive",
        "web_tour",
        # Tier Validation Modules
        "account_move_tier_validation",
        "account_move_tier_validation_approver",
        "account_move_tier_validation_forward",
        "account_payment_order_tier_validation",
        "hr_personal_equipment_request_tier_validation",
        "purchase_request_tier_validation",
        "purchase_tier_validation",
        "purchase_work_acceptance_tier_validation",
        "sale_tier_validation",
        "stock_picking_tier_validation",
        "stock_request_tier_validation",
    ],
    "data": [],
    "demo": [],
}
